# リリースノートのテンプレート

changelog:
  exclude:
    labels:
      - "release"  # このラベルが付いているPRはリリースノートから除外
  categories:
    - title: "新機能 🎉"
      labels:
        - "enhancement"
    - title: "修正 🐛"
      labels:
        - "bug"
    - title: "テスト 🔍️"
      labels:
        - "test"
    - title: "その他"
      labels:
        - "*"  # 何も該当しないラベル付きPRはここに入る
