name: flutter Analysis

on:
 pull_request:
  branches:
   - main

jobs:
  analyze:
    name: Analyze
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 1

    - name: Set up Dart
      uses: subosito/flutter-action@v1
      with:
        channel: 'stable'

    - name: Clean up
      run: flutter clean

    - name: Install dependencies
      run: flutter pub get
    
    - name: Run build runner
      run: flutter pub run build_runner build --delete-conflicting-outputs

    - name: Run analyzer
      run: flutter analyze

    - name: Run tests
      run: flutter test
